import type { Course } from "../types";

const defaultModules = (topics: string[]) => [
  { title: "Fundamentals", topics: topics.slice(0, 3), duration: "2 weeks" },
  { title: "Core Concepts", topics: topics.slice(3, 6), duration: "3 weeks" },
  { title: "Advanced Topics", topics: topics.slice(6), duration: "2 weeks" },
  {
    title: "Projects & Assessment",
    topics: ["Capstone Project", "Code Review", "Final Assessment"],
    duration: "1 week",
  },
];

const defaultFaqs = (courseName: string) => [
  {
    question: `Do I need prior experience for ${courseName}?`,
    answer:
      "No prior experience is required for our beginner courses. We start from the fundamentals and gradually progress to advanced topics.",
  },
  {
    question: "Will I get a certificate?",
    answer:
      "Yes, upon successful completion of the course and final project, you will receive an industry-recognized certificate from YahTecInfo.",
  },
  {
    question: "Is placement assistance provided?",
    answer:
      "Absolutely! We provide resume building, mock interviews, and direct referrals to our 50+ hiring partners.",
  },
  {
    question: "Can I access recordings?",
    answer:
      "Yes, all live sessions are recorded and available for lifetime access through our learning portal.",
  },
];

export const COURSES: Course[] = [
  {
    id: "html-css",
    title: "HTML & CSS",
    slug: "/courses/html-css",
    category: "Frontend",
    description:
      "Master the building blocks of the web. Learn semantic HTML5, modern CSS3, Flexbox, Grid, animations, and responsive design principles to create stunning websites.",
    shortDescription: "Build beautiful, responsive websites from scratch.",
    duration: "6 weeks",
    level: "Beginner",
    rating: 4.9,
    students: 1200,
    price: "₹9,999",
    icon: "FaHtml5",
    color: "#E44D26",
    modules: defaultModules([
      "HTML5 Structure",
      "Semantic Elements",
      "Forms & Inputs",
      "CSS Selectors",
      "Flexbox Layout",
      "CSS Grid",
      "Animations",
      "Responsive Design",
    ]),
    projects: ["Personal Portfolio", "Landing Page", "Dashboard UI"],
    tools: ["VS Code", "Chrome DevTools", "Figma"],
    career: ["Frontend Developer", "UI Developer", "Web Designer"],
    requirements: ["Basic computer knowledge", "No coding experience needed"],
    faqs: defaultFaqs("HTML & CSS"),
  },
  {
    id: "javascript",
    title: "JavaScript",
    slug: "/courses/javascript",
    category: "Frontend",
    description:
      "Deep dive into JavaScript ES6+, DOM manipulation, async programming, APIs, and modern JavaScript patterns used in production applications.",
    shortDescription: "Master the language of the web with modern JS.",
    duration: "8 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 980,
    price: "₹14,999",
    icon: "FaJs",
    color: "#F7DF1E",
    modules: defaultModules([
      "Variables & Data Types",
      "Functions & Scope",
      "DOM Manipulation",
      "ES6+ Features",
      "Async/Await",
      "Fetch API",
      "Error Handling",
      "Design Patterns",
    ]),
    projects: ["Todo App", "Weather App", "E-commerce Cart"],
    tools: ["VS Code", "Node.js", "Chrome DevTools"],
    career: [
      "JavaScript Developer",
      "Frontend Developer",
      "Full Stack Developer",
    ],
    requirements: ["HTML & CSS basics"],
    faqs: defaultFaqs("JavaScript"),
  },
  {
    id: "typescript",
    title: "TypeScript",
    slug: "/courses/typescript",
    category: "Frontend",
    description:
      "Master TypeScript to build scalable, maintainable, and type-safe applications. Learn static typing, interfaces, generics, classes, modules, and advanced TypeScript features used in modern React and Angular development.",
    shortDescription: "Build type-safe and scalable web applications.",
    duration: "6 weeks",
    level: "Intermediate",
    rating: 4.9,
    students: 720,
    price: "₹12,999",
    icon: "SiTypescript",
    color: "#3178C6",
    modules: defaultModules([
      "Introduction to TypeScript",
      "Types & Interfaces",
      "Functions & Classes",
      "Generics",
      "Modules & Namespaces",
      "Advanced Types",
      "TypeScript with React",
      "Final Project",
    ]),
    projects: ["Task Manager", "Inventory System", "React TypeScript App"],
    tools: ["VS Code", "TypeScript", "Node.js"],
    career: ["Frontend Developer", "React Developer", "Full Stack Developer"],
    requirements: ["JavaScript knowledge"],
    faqs: defaultFaqs("TypeScript"),
  },
  {
    id: "reactjs",
    title: "React JS",
    slug: "/courses/reactjs",
    category: "Frontend",
    description:
      "Build modern, scalable web applications with React 19. Learn hooks, state management, routing, and best practices for enterprise applications.",
    shortDescription: "Build dynamic UIs with the most popular framework.",
    duration: "10 weeks",
    level: "Intermediate",
    rating: 4.9,
    students: 850,
    price: "₹19,999",
    icon: "FaReact",
    color: "#61DAFB",
    modules: defaultModules([
      "JSX & Components",
      "Props & State",
      "Hooks Deep Dive",
      "Context API",
      "React Router",
      "Performance",
      "Testing",
      "Deployment",
    ]),
    projects: ["Social Media App", "Admin Dashboard", "Real-time Chat App"],
    tools: ["VS Code", "Vite", "React DevTools"],
    career: ["React Developer", "Frontend Engineer", "Full Stack Developer"],
    requirements: ["JavaScript proficiency", "HTML & CSS"],
    faqs: defaultFaqs("React JS"),
  },
  {
    id: "java",
    title: "Java Programming",
    slug: "/courses/java",
    category: "Backend",
    description:
      "Learn Java from fundamentals to advanced OOP, collections, multithreading, and design patterns used in enterprise software development.",
    shortDescription: "Enterprise-grade programming with Java.",
    duration: "10 weeks",
    level: "Beginner",
    rating: 4.7,
    students: 720,
    price: "₹17,999",
    icon: "FaJava",
    color: "#007396",
    modules: defaultModules([
      "Java Basics",
      "OOP Concepts",
      "Collections Framework",
      "Exception Handling",
      "Multithreading",
      "JDBC",
      "Design Patterns",
      "Project",
    ]),
    projects: ["Banking System", "Library Management", "E-commerce Backend"],
    tools: ["IntelliJ IDEA", "Maven", "Git"],
    career: ["Java Developer", "Backend Engineer", "Software Engineer"],
    requirements: ["Basic programming logic"],
    faqs: defaultFaqs("Java"),
  },
  {
    id: "springboot",
    title: "Spring Boot",
    slug: "/courses/springboot",
    category: "Backend",
    description:
      "Build production-ready REST APIs and microservices with Spring Boot, Spring Security, JPA, and cloud deployment strategies.",
    shortDescription: "Enterprise backend development with Spring.",
    duration: "8 weeks",
    level: "Intermediate",
    rating: 4.8,
    students: 560,
    price: "₹21,999",
    icon: "SiSpringboot",
    color: "#6DB33F",
    modules: defaultModules([
      "Spring Core",
      "Spring Boot Setup",
      "REST APIs",
      "Spring Security",
      "JPA/Hibernate",
      "Microservices",
      "Testing",
      "Deployment",
    ]),
    projects: ["REST API Service", "Microservice Architecture", "Auth System"],
    tools: ["IntelliJ IDEA", "Postman", "Docker"],
    career: ["Spring Developer", "Backend Engineer", "Microservices Architect"],
    requirements: ["Java proficiency"],
    faqs: defaultFaqs("Spring Boot"),
  },
  {
    id: "python",
    title: "Python",
    slug: "/courses/python",
    category: "Backend",
    description:
      "Master Python for web development, data analysis, automation, and scripting. From basics to building real-world applications.",
    shortDescription: "Versatile programming for web, data & automation.",
    duration: "8 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 890,
    price: "₹15,999",
    icon: "FaPython",
    color: "#3776AB",
    modules: defaultModules([
      "Python Basics",
      "Data Structures",
      "OOP in Python",
      "File Handling",
      "Web Scraping",
      "Django Basics",
      "API Development",
      "Project",
    ]),
    projects: ["Web Scraper", "Django Blog", "Data Analysis Tool"],
    tools: ["PyCharm", "Jupyter", "pip"],
    career: ["Python Developer", "Data Analyst", "Automation Engineer"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("Python"),
  },
  {
    id: "aws",
    title: "AWS Cloud",
    slug: "/courses/aws",
    category: "Cloud",
    description:
      "Learn Amazon Web Services from EC2 to Lambda. Deploy, scale, and manage cloud infrastructure with hands-on labs.",
    shortDescription: "Cloud computing with Amazon Web Services.",
    duration: "6 weeks",
    level: "Intermediate",
    rating: 4.7,
    students: 430,
    price: "₹22,999",
    icon: "FaAws",
    color: "#FF9900",
    modules: defaultModules([
      "Cloud Fundamentals",
      "EC2 & VPC",
      "S3 & Storage",
      "RDS & Databases",
      "Lambda & Serverless",
      "IAM & Security",
      "DevOps on AWS",
      "Certification Prep",
    ]),
    projects: ["Deploy Web App", "Serverless API", "Multi-tier Architecture"],
    tools: ["AWS Console", "AWS CLI", "CloudFormation"],
    career: ["Cloud Engineer", "DevOps Engineer", "Solutions Architect"],
    requirements: ["Basic networking knowledge"],
    faqs: defaultFaqs("AWS"),
  },
  {
    id: "manual-testing",
    title: "Manual Testing",
    slug: "/courses/manual-testing",
    category: "QA",
    description:
      "Learn Manual Testing from beginner to advanced. Master SDLC, STLC, test case design, bug reporting, Agile methodology, API testing basics, and real-world software testing practices.",
    shortDescription: "Become a professional Manual Testing Engineer.",
    duration: "6 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 850,
    price: "₹11,999",
    icon: "FaBug",
    color: "#FF6B6B",
    modules: defaultModules([
      "Software Testing Basics",
      "SDLC & STLC",
      "Test Case Design",
      "Bug Life Cycle",
      "Agile Testing",
      "API Testing Basics",
      "Test Documentation",
      "Final Project",
    ]),
    projects: [
      "Web Application Testing",
      "Mobile App Testing",
      "Bug Tracking Project",
    ],
    tools: ["JIRA", "Postman", "TestRail"],
    career: ["Manual Test Engineer", "QA Analyst", "Software Tester"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("Manual Testing"),
  },
  {
    id: "automation",
    title: "Test Automation",
    slug: "/courses/automation",
    category: "QA",
    description:
      "Automate testing with Selenium, Cypress, and JUnit. Build robust test frameworks for web and API automation.",
    shortDescription: "Automate testing with industry tools.",
    duration: "8 weeks",
    level: "Intermediate",
    rating: 4.8,
    students: 480,
    price: "₹18,999",
    icon: "FaRobot",
    color: "#00FF99",
    modules: defaultModules([
      "Automation Basics",
      "Selenium WebDriver",
      "Page Object Model",
      "Cypress",
      "API Automation",
      "Framework Design",
      "CI/CD Integration",
      "Project",
    ]),
    projects: ["Selenium Framework", "Cypress E2E Suite", "CI Pipeline"],
    tools: ["Selenium", "Cypress", "Jenkins"],
    career: ["Automation Engineer", "SDET", "QA Architect"],
    requirements: ["Java or JavaScript basics", "Testing fundamentals"],
    faqs: defaultFaqs("Test Automation"),
  },
  {
    id: "mysql",
    title: "MySQL Database",
    slug: "/courses/mysql",
    category: "Database",
    description:
      "Master SQL queries, database design, normalization, stored procedures, and optimization for high-performance applications.",
    shortDescription: "Database design and SQL mastery.",
    duration: "4 weeks",
    level: "Beginner",
    rating: 4.7,
    students: 540,
    price: "₹9,999",
    icon: "SiMysql",
    color: "#4479A1",
    modules: defaultModules([
      "SQL Basics",
      "Joins & Subqueries",
      "Database Design",
      "Normalization",
      "Stored Procedures",
      "Indexing",
      "Performance Tuning",
      "Project",
    ]),
    projects: ["E-commerce DB Design", "Reporting System", "Data Migration"],
    tools: ["MySQL Workbench", "phpMyAdmin", "DBeaver"],
    career: ["Database Administrator", "Backend Developer", "Data Engineer"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("MySQL"),
  },
  {
    id: "git",
    title: "Git Version Control",
    slug: "/courses/git",
    category: "DevOps",
    description:
      "Learn Git workflows, branching strategies, merging, rebasing, and collaboration techniques used in professional development teams.",
    shortDescription: "Professional version control with Git.",
    duration: "2 weeks",
    level: "Beginner",
    rating: 4.9,
    students: 1100,
    price: "₹4,999",
    icon: "FaGitAlt",
    color: "#F05032",
    modules: defaultModules([
      "Git Basics",
      "Branching",
      "Merging & Rebasing",
      "Remote Repos",
      "Git Flow",
      "Conflict Resolution",
      "Best Practices",
      "Workshop",
    ]),
    projects: ["Team Collaboration Project", "Open Source Contribution"],
    tools: ["Git", "Git Bash", "GitKraken"],
    career: ["Any Developer Role"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("Git"),
  },
  {
    id: "github",
    title: "GitHub",
    slug: "/courses/github",
    category: "DevOps",
    description:
      "Master GitHub for code hosting, pull requests, code reviews, GitHub Actions CI/CD, and open-source contribution.",
    shortDescription: "Collaborate and deploy with GitHub.",
    duration: "2 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 950,
    price: "₹4,999",
    icon: "FaGithub",
    color: "#FFFFFF",
    modules: defaultModules([
      "GitHub Setup",
      "Repositories",
      "Pull Requests",
      "Code Reviews",
      "GitHub Actions",
      "Pages & Deployment",
      "Open Source",
      "Portfolio",
    ]),
    projects: ["Portfolio on GitHub Pages", "CI/CD Pipeline"],
    tools: ["GitHub", "GitHub Actions", "GitHub Copilot"],
    career: ["Any Developer Role"],
    requirements: ["Git basics"],
    faqs: defaultFaqs("GitHub"),
  },
  {
    id: "fullstack",
    title: "Full Stack Development",
    slug: "/courses/fullstack",
    category: "Full Stack",
    description:
      "Complete full stack program covering React, Node.js, databases, and deployment. Build end-to-end applications from scratch.",
    shortDescription: "End-to-end web development mastery.",
    duration: "16 weeks",
    level: "Advanced",
    rating: 4.9,
    students: 620,
    price: "₹39,999",
    icon: "FaLayerGroup",
    color: "#00E5FF",
    modules: defaultModules([
      "Frontend with React",
      "Backend with Node.js",
      "Database Design",
      "Authentication",
      "API Development",
      "DevOps & Deployment",
      "Capstone Project",
      "Interview Prep",
    ]),
    projects: ["SaaS Application", "Social Platform", "E-commerce Platform"],
    tools: ["React", "Node.js", "MongoDB", "AWS"],
    career: ["Full Stack Developer", "Software Engineer", "Tech Lead"],
    requirements: ["HTML, CSS, JavaScript basics"],
    faqs: defaultFaqs("Full Stack Development"),
  },
  {
    id: "resume",
    title: "Resume Building",
    slug: "/courses/resume",
    category: "Career",
    description:
      "Craft a professional tech resume that gets past ATS systems and impresses hiring managers.",
    shortDescription: "Build a resume that gets you hired.",
    duration: "1 week",
    level: "Beginner",
    rating: 4.8,
    students: 2000,
    price: "Free",
    icon: "FaFileAlt",
    color: "#FFD700",
    modules: [
      {
        title: "Resume Workshop",
        topics: [
          "ATS Optimization",
          "Format & Structure",
          "Skills Section",
          "Project Showcase",
        ],
        duration: "1 week",
      },
    ],
    projects: ["Professional Resume"],
    tools: ["Canva", "LinkedIn"],
    career: ["All Tech Roles"],
    requirements: ["None"],
    faqs: defaultFaqs("Resume Building"),
  },
  {
    id: "interview",
    title: "Interview Preparation",
    slug: "/courses/interview",
    category: "Career",
    description:
      "Comprehensive interview prep covering technical questions, coding challenges, and behavioral interviews.",
    shortDescription: "Ace your tech interviews with confidence.",
    duration: "2 weeks",
    level: "Intermediate",
    rating: 4.9,
    students: 1500,
    price: "₹7,999",
    icon: "FaUserTie",
    color: "#8B5CF6",
    modules: [
      {
        title: "Interview Mastery",
        topics: [
          "Technical Questions",
          "Coding Challenges",
          "System Design",
          "Behavioral Rounds",
        ],
        duration: "2 weeks",
      },
    ],
    projects: ["Interview Question Bank"],
    tools: ["LeetCode", "HackerRank"],
    career: ["All Tech Roles"],
    requirements: ["Course completion in any tech stack"],
    faqs: defaultFaqs("Interview Preparation"),
  },
  {
    id: "mock-interview",
    title: "Mock Interview",
    slug: "/courses/mock-interview",
    category: "Career",
    description:
      "Practice with industry experts in simulated interview environments with detailed feedback.",
    shortDescription: "Real interview simulation with expert feedback.",
    duration: "1 week",
    level: "Advanced",
    rating: 4.9,
    students: 800,
    price: "₹5,999",
    icon: "FaComments",
    color: "#3B82F6",
    modules: [
      {
        title: "Mock Sessions",
        topics: [
          "HR Round",
          "Technical Round",
          "Coding Round",
          "Feedback Session",
        ],
        duration: "1 week",
      },
    ],
    projects: ["Performance Report"],
    tools: ["Zoom", "CoderPad"],
    career: ["All Tech Roles"],
    requirements: ["Interview prep completion"],
    faqs: defaultFaqs("Mock Interview"),
  },
  {
    id: "soft-skills",
    title: "Soft Skills",
    slug: "/courses/soft-skills",
    category: "Career",
    description:
      "Develop communication, teamwork, leadership, and presentation skills essential for tech professionals.",
    shortDescription: "Essential professional skills for tech careers.",
    duration: "2 weeks",
    level: "Beginner",
    rating: 4.7,
    students: 1200,
    price: "₹6,999",
    icon: "FaUsers",
    color: "#00FF99",
    modules: [
      {
        title: "Professional Development",
        topics: [
          "Communication",
          "Teamwork",
          "Leadership",
          "Presentation Skills",
        ],
        duration: "2 weeks",
      },
    ],
    projects: ["Presentation Portfolio"],
    tools: ["PowerPoint", "Zoom"],
    career: ["All Tech Roles"],
    requirements: ["None"],
    faqs: defaultFaqs("Soft Skills"),
  },
  {
    id: "ms-office",
    title: "Microsoft Office",
    slug: "/courses/ms-office",
    category: "Basic Computer",
    description:
      "Master Microsoft Word, Excel, PowerPoint, and Outlook for professional office work and productivity.",
    shortDescription: "Become an expert in Microsoft Office.",
    duration: "6 weeks",
    level: "Beginner",
    rating: 4.9,
    students: 1200,
    price: "₹6,999",
    icon: "FaMicrosoft",
    color: "#0078D4",
    modules: defaultModules([
      "MS Word",
      "MS Excel",
      "MS PowerPoint",
      "MS Outlook",
      "Advanced Excel",
      "Charts & Formulas",
      "Presentation Design",
      "Final Project",
    ]),
    projects: ["Resume Design", "Excel Payroll", "Business Presentation"],
    tools: ["Word", "Excel", "PowerPoint"],
    career: ["Office Executive", "Data Entry Operator", "Administrator"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("Microsoft Office"),
  },
  {
    id: "ms-paint",
    title: "MS Paint",
    slug: "/courses/ms-paint",
    category: "Basic Computer",
    description:
      "Learn Microsoft Paint from basics to advanced drawing techniques. Create digital artwork, edit images, design posters, and understand essential graphic editing tools.",
    shortDescription: "Learn digital drawing and image editing with MS Paint.",
    duration: "2 weeks",
    level: "Beginner",
    rating: 4.7,
    students: 350,
    price: "₹2,999",
    icon: "FaPaintBrush",
    color: "#4CAF50",
    modules: defaultModules([
      "Paint Interface",
      "Drawing Tools",
      "Shapes & Colors",
      "Text Tool",
      "Image Editing",
      "Resize & Crop",
      "Saving Images",
      "Mini Project",
    ]),
    projects: ["Greeting Card", "Logo Design", "Poster Design"],
    tools: ["MS Paint", "Windows"],
    career: ["Office Assistant", "Graphic Assistant", "Computer Operator"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("MS Paint"),
  },
  {
    id: "dtp",
    title: "Desktop Publishing (DTP)",
    slug: "/courses/dtp",
    category: "Design",
    description:
      "Master Desktop Publishing (DTP) using industry-standard tools like Adobe InDesign, CorelDRAW, and PageMaker. Learn professional layout design, typography, image editing basics, and print-ready document creation for publishing, advertising, and branding.",
    shortDescription: "Create professional print and publishing designs.",
    duration: "8 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 540,
    price: "₹12,999",
    icon: "FaNewspaper",
    color: "#9C27B0",
    modules: defaultModules([
      "Introduction to DTP",
      "Typography & Fonts",
      "Page Layout Design",
      "CorelDRAW Basics",
      "Adobe InDesign",
      "Adobe PageMaker",
      "Print & Publishing",
      "Final Project",
    ]),
    projects: [
      "Business Card Design",
      "Magazine Layout",
      "Brochure & Flyer Design",
    ],
    tools: [
      "Adobe InDesign",
      "CorelDRAW",
      "Adobe PageMaker",
      "Adobe Photoshop",
    ],
    career: [
      "DTP Operator",
      "Graphic Designer",
      "Publishing Executive",
      "Print Production Designer",
    ],
    requirements: ["Basic computer knowledge", "No design experience required"],
    faqs: defaultFaqs("Desktop Publishing (DTP)"),
  },

  {
    id: "photoshop",
    title: "Adobe Photoshop",
    slug: "/courses/photoshop",
    category: "Design",
    description:
      "Master Adobe Photoshop from beginner to advanced. Learn photo editing, retouching, color correction, digital painting, banner creation, social media graphics, and professional graphic design techniques.",
    shortDescription: "Create stunning graphics and professional photo edits.",
    duration: "8 weeks",
    level: "Beginner",
    rating: 4.9,
    students: 850,
    price: "₹14,999",
    icon: "SiAdobephotoshop",
    color: "#31A8FF",
    modules: defaultModules([
      "Photoshop Interface",
      "Selection Tools",
      "Layers & Masks",
      "Photo Retouching",
      "Color Correction",
      "Typography Design",
      "Social Media Posters",
      "Final Project",
    ]),
    projects: [
      "Social Media Banner",
      "Photo Manipulation",
      "Business Poster Design",
    ],
    tools: ["Adobe Photoshop", "Adobe Bridge", "Adobe Camera Raw"],
    career: [
      "Graphic Designer",
      "Photo Editor",
      "Digital Artist",
      "Creative Designer",
    ],
    requirements: [
      "Basic computer knowledge",
      "No prior design experience required",
    ],
    faqs: defaultFaqs("Adobe Photoshop"),
  },
  {
    id: "php-programming",
    title: "PHP Programming",
    slug: "/courses/php-programming",
    category: "Backend",
    description:
      "Learn PHP from fundamentals to advanced web development. Build dynamic websites, REST APIs, authentication systems, database-driven applications, and modern backend solutions using PHP and MySQL.",
    shortDescription:
      "Build dynamic websites and powerful backend applications.",
    duration: "10 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 780,
    price: "₹16,999",
    icon: "FaPhp",
    color: "#777BB4",
    modules: defaultModules([
      "PHP Basics",
      "Variables & Data Types",
      "Functions & Arrays",
      "Forms & Validation",
      "Sessions & Cookies",
      "MySQL Integration",
      "REST API Development",
      "Mini Project",
    ]),
    projects: [
      "Student Management System",
      "E-Commerce Backend",
      "Authentication System",
    ],
    tools: ["VS Code", "XAMPP", "PHP", "MySQL", "Postman"],
    career: [
      "PHP Developer",
      "Backend Developer",
      "Full Stack Developer",
      "Web Application Developer",
    ],
    requirements: ["Basic HTML & CSS knowledge", "Basic programming knowledge"],
    faqs: defaultFaqs("PHP Programming"),
  },
  {
    id: "c-programming",
    title: "C Programming",
    slug: "/courses/c-programming",
    category: "Programming",
    description:
      "Learn C Programming from basics to advanced concepts. Master variables, loops, functions, arrays, pointers, file handling, and data structures while building real-world applications.",
    shortDescription: "Build a strong programming foundation with C.",
    duration: "8 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 950,
    price: "₹11,999",
    icon: "SiC",
    color: "#00599C",
    modules: defaultModules([
      "Introduction to C",
      "Variables & Data Types",
      "Operators & Control Statements",
      "Functions",
      "Arrays & Strings",
      "Pointers",
      "File Handling",
      "Mini Project",
    ]),
    projects: [
      "Student Management System",
      "Bank Management System",
      "Library Management System",
    ],
    tools: ["VS Code", "GCC Compiler", "Code::Blocks"],
    career: [
      "Software Developer",
      "Embedded Systems Developer",
      "System Programmer",
    ],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("C Programming"),
  },
  {
    id: "cpp-programming",
    title: "C++ Programming",
    slug: "/courses/cpp-programming",
    category: "Programming",
    description:
      "Master C++ programming with object-oriented programming concepts, STL, classes, inheritance, polymorphism, exception handling, and modern C++ development.",
    shortDescription: "Master object-oriented programming with C++.",
    duration: "10 weeks",
    level: "Beginner",
    rating: 4.9,
    students: 870,
    price: "₹13,999",
    icon: "SiCplusplus",
    color: "#00599C",
    modules: defaultModules([
      "C++ Basics",
      "Functions & Classes",
      "Object-Oriented Programming",
      "Inheritance & Polymorphism",
      "Templates & STL",
      "Exception Handling",
      "File Handling",
      "Final Project",
    ]),
    projects: [
      "Hospital Management System",
      "Inventory Management",
      "ATM Simulation",
    ],
    tools: ["VS Code", "Visual Studio", "GCC/G++"],
    career: ["C++ Developer", "Game Developer", "Software Engineer"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("C++ Programming"),
  },

  {
    id: "scss",
    title: "SCSS",
    slug: "/courses/scss",
    category: "Frontend",
    description:
      "Master SCSS to write clean, reusable, and maintainable styles using variables, mixins, nesting, functions, and modular architecture.",
    shortDescription: "Write scalable and maintainable CSS with SCSS.",
    duration: "3 weeks",
    level: "Intermediate",
    rating: 4.8,
    students: 620,
    price: "₹6,999",
    icon: "SiSass",
    color: "#CC6699",
    modules: defaultModules([
      "Introduction to SCSS",
      "Variables",
      "Nesting",
      "Mixins",
      "Functions",
      "Partials",
      "Responsive SCSS",
      "Project",
    ]),
    projects: ["SCSS Design System", "Responsive Website", "Admin Dashboard"],
    tools: ["VS Code", "Sass Compiler", "Vite"],
    career: ["Frontend Developer", "UI Developer", "Web Designer"],
    requirements: ["Basic CSS knowledge"],
    faqs: defaultFaqs("SCSS"),
  },

  {
    id: "angular",
    title: "Angular",
    slug: "/courses/angular",
    category: "Frontend",
    description:
      "Learn Angular from beginner to advanced. Build enterprise-grade single-page applications using components, services, routing, forms, RxJS, HTTP Client, and state management.",
    shortDescription: "Develop powerful enterprise web applications.",
    duration: "10 weeks",
    level: "Intermediate",
    rating: 4.8,
    students: 650,
    price: "₹18,999",
    icon: "FaAngular",
    color: "#DD0031",
    modules: defaultModules([
      "Angular Fundamentals",
      "Components & Templates",
      "Routing",
      "Services & Dependency Injection",
      "Reactive Forms",
      "RxJS",
      "REST API Integration",
      "Deployment",
    ]),
    projects: [
      "Employee Management",
      "E-Commerce Dashboard",
      "Hospital Management System",
    ],
    tools: ["Angular CLI", "VS Code", "Postman"],
    career: ["Angular Developer", "Frontend Developer", "Software Engineer"],
    requirements: ["HTML, CSS & JavaScript knowledge"],
    faqs: defaultFaqs("Angular"),
  },
  {
    id: "nodejs",
    title: "Node.js",
    slug: "/courses/nodejs",
    category: "Backend",
    description:
      "Master Node.js for backend development. Learn Express.js, REST APIs, authentication, JWT, file uploads, real-time applications, and database integration with MongoDB and MySQL.",
    shortDescription: "Build fast and scalable backend applications.",
    duration: "10 weeks",
    level: "Intermediate",
    rating: 4.9,
    students: 890,
    price: "₹18,999",
    icon: "FaNodeJs",
    color: "#339933",
    modules: defaultModules([
      "Node.js Fundamentals",
      "Express.js",
      "REST APIs",
      "Authentication & JWT",
      "Database Integration",
      "File Upload",
      "Socket.IO",
      "Deployment",
    ]),
    projects: ["REST API", "Chat Application", "E-Commerce Backend"],
    tools: ["Node.js", "Express.js", "MongoDB", "Postman"],
    career: ["Node.js Developer", "Backend Developer", "Full Stack Developer"],
    requirements: ["JavaScript knowledge"],
    faqs: defaultFaqs("Node.js"),
  },
  {
    id: "linux",
    title: "Linux",
    slug: "/courses/linux",
    category: "Operating System",
    description:
      "Learn Linux administration from beginner to advanced. Master terminal commands, shell scripting, file management, permissions, networking, package management, and server administration.",
    shortDescription: "Master Linux command line and system administration.",
    duration: "6 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 540,
    price: "₹9,999",
    icon: "FaLinux",
    color: "#FCC624",
    modules: defaultModules([
      "Linux Introduction",
      "Terminal Commands",
      "File System",
      "Permissions",
      "Shell Scripting",
      "Package Management",
      "Networking",
      "Server Administration",
    ]),
    projects: [
      "Shell Script Automation",
      "Linux Server Setup",
      "User Management System",
    ],
    tools: ["Ubuntu", "Terminal", "Bash"],
    career: ["Linux Administrator", "System Administrator", "DevOps Engineer"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("Linux"),
  },
  {
    id: "laravel",
    title: "Laravel",
    slug: "/courses/laravel",
    category: "Backend",
    description:
      "Master Laravel from beginner to advanced. Learn MVC architecture, routing, authentication, Eloquent ORM, REST APIs, middleware, queues, and deployment by building production-ready web applications.",
    shortDescription: "Build modern PHP web applications with Laravel.",
    duration: "10 weeks",
    level: "Intermediate",
    rating: 4.9,
    students: 680,
    price: "₹19,999",
    icon: "FaLaravel",
    color: "#FF2D20",
    modules: defaultModules([
      "Laravel Fundamentals",
      "MVC Architecture",
      "Routing & Controllers",
      "Blade Templates",
      "Authentication",
      "Eloquent ORM",
      "REST API Development",
      "Deployment",
    ]),
    projects: [
      "Blog Management System",
      "E-Commerce Website",
      "Inventory Management System",
    ],
    tools: ["Laravel", "Composer", "VS Code", "MySQL"],
    career: ["Laravel Developer", "PHP Developer", "Backend Developer"],
    requirements: ["PHP knowledge"],
    faqs: defaultFaqs("Laravel"),
  },
  {
    id: "jdbc",
    title: "JDBC",
    slug: "/courses/jdbc",
    category: "Backend",
    description:
      "Learn Java Database Connectivity (JDBC) to build database-driven Java applications. Master CRUD operations, prepared statements, transactions, connection pooling, and exception handling.",
    shortDescription: "Connect Java applications with relational databases.",
    duration: "4 weeks",
    level: "Intermediate",
    rating: 4.8,
    students: 420,
    price: "₹8,999",
    icon: "FaDatabase",
    color: "#007396",
    modules: defaultModules([
      "JDBC Introduction",
      "Database Connections",
      "CRUD Operations",
      "Prepared Statements",
      "Transactions",
      "Batch Processing",
      "Connection Pooling",
      "Mini Project",
    ]),
    projects: [
      "Student Management System",
      "Employee Database",
      "Inventory System",
    ],
    tools: ["Java", "JDBC", "MySQL", "PostgreSQL"],
    career: ["Java Developer", "Backend Developer", "Software Engineer"],
    requirements: ["Java Programming", "Basic SQL knowledge"],
    faqs: defaultFaqs("JDBC"),
  },
  {
    id: "r2dbc",
    title: "R2DBC",
    slug: "/courses/r2dbc",
    category: "Backend",
    description:
      "Master Reactive Relational Database Connectivity (R2DBC) with Spring Boot. Learn reactive programming, asynchronous database access, repositories, transactions, and scalable application development.",
    shortDescription: "Build reactive database applications with Spring Boot.",
    duration: "4 weeks",
    level: "Advanced",
    rating: 4.8,
    students: 280,
    price: "₹10,999",
    icon: "FaDatabase",
    color: "#6DB33F",
    modules: defaultModules([
      "Reactive Programming",
      "R2DBC Setup",
      "Reactive CRUD",
      "Repositories",
      "Transactions",
      "Spring WebFlux",
      "Performance Optimization",
      "Project",
    ]),
    projects: ["Reactive REST API", "Inventory Service", "Employee Management"],
    tools: ["Spring Boot", "R2DBC", "PostgreSQL", "IntelliJ IDEA"],
    career: [
      "Spring Boot Developer",
      "Backend Developer",
      "Reactive Java Developer",
    ],
    requirements: ["Java", "Spring Boot", "SQL knowledge"],
    faqs: defaultFaqs("R2DBC"),
  },
  {
    id: "postgresql",
    title: "PostgreSQL",
    slug: "/courses/postgresql",
    category: "Database",
    description:
      "Learn PostgreSQL from beginner to advanced. Master SQL queries, database design, indexing, stored procedures, functions, transactions, and performance optimization.",
    shortDescription: "Master enterprise-grade PostgreSQL databases.",
    duration: "6 weeks",
    level: "Beginner",
    rating: 4.8,
    students: 540,
    price: "₹9,999",
    icon: "SiPostgresql",
    color: "#336791",
    modules: defaultModules([
      "PostgreSQL Basics",
      "SQL Queries",
      "Joins & Views",
      "Functions",
      "Stored Procedures",
      "Transactions",
      "Indexes",
      "Project",
    ]),
    projects: [
      "Library Database",
      "Hospital Management Database",
      "E-Commerce Database",
    ],
    tools: ["PostgreSQL", "pgAdmin", "DBeaver"],
    career: ["Database Administrator", "Backend Developer", "Data Engineer"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("PostgreSQL"),
  },
  {
    id: "mysql",
    title: "MySQL",
    slug: "/courses/mysql",
    category: "Database",
    description:
      "Master MySQL database development with SQL queries, normalization, joins, stored procedures, triggers, indexing, and database optimization for real-world applications.",
    shortDescription: "Learn SQL and database management using MySQL.",
    duration: "6 weeks",
    level: "Beginner",
    rating: 4.9,
    students: 920,
    price: "₹9,999",
    icon: "SiMysql",
    color: "#4479A1",
    modules: defaultModules([
      "MySQL Fundamentals",
      "CRUD Operations",
      "Joins & Subqueries",
      "Normalization",
      "Stored Procedures",
      "Triggers",
      "Indexes",
      "Final Project",
    ]),
    projects: [
      "College Management Database",
      "Sales Management System",
      "Online Store Database",
    ],
    tools: ["MySQL", "MySQL Workbench", "phpMyAdmin"],
    career: [
      "Database Developer",
      "Backend Developer",
      "Database Administrator",
    ],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("MySQL"),
  },
  {
    id: "mongodb",
    title: "MongoDB",
    slug: "/courses/mongodb",
    category: "Database",
    description:
      "Learn MongoDB from beginner to advanced. Master NoSQL databases, collections, documents, aggregation, indexing, schema design, and integration with Node.js and modern web applications.",
    shortDescription: "Build scalable NoSQL database applications.",
    duration: "6 weeks",
    level: "Intermediate",
    rating: 4.9,
    students: 710,
    price: "₹12,999",
    icon: "SiMongodb",
    color: "#47A248",
    modules: defaultModules([
      "MongoDB Fundamentals",
      "Collections & Documents",
      "CRUD Operations",
      "Aggregation Framework",
      "Indexes",
      "Schema Design",
      "MongoDB Atlas",
      "Final Project",
    ]),
    projects: [
      "Blog API Database",
      "E-Commerce Database",
      "Chat Application Backend",
    ],
    tools: ["MongoDB", "MongoDB Compass", "MongoDB Atlas"],
    career: ["MongoDB Developer", "Backend Developer", "Full Stack Developer"],
    requirements: ["Basic database knowledge"],
    faqs: defaultFaqs("MongoDB"),
  },

  {
    id: "numpy",
    title: "NumPy",
    slug: "/courses/numpy",
    category: "Data Science",
    description:
      "Master NumPy for scientific computing and data analysis. Learn arrays, matrix operations, broadcasting, mathematical functions, indexing, and numerical computing for Python applications.",
    shortDescription: "Powerful numerical computing with Python.",
    duration: "4 weeks",
    level: "Intermediate",
    rating: 4.8,
    students: 520,
    price: "₹8,999",
    icon: "SiNumpy",
    color: "#013243",
    modules: defaultModules([
      "NumPy Introduction",
      "Arrays & Indexing",
      "Array Operations",
      "Broadcasting",
      "Mathematical Functions",
      "Linear Algebra",
      "Random Module",
      "Mini Project",
    ]),
    projects: ["Data Analysis", "Scientific Calculator", "Matrix Operations"],
    tools: ["Python", "NumPy", "Jupyter Notebook"],
    career: ["Python Developer", "Data Analyst", "Data Scientist"],
    requirements: ["Python Programming"],
    faqs: defaultFaqs("NumPy"),
  },
  {
    id: "pytest",
    title: "PyTest",
    slug: "/courses/pytest",
    category: "QA",
    description:
      "Learn PyTest for Python test automation. Master unit testing, fixtures, assertions, parameterization, mocking, reporting, and API automation with real-world projects.",
    shortDescription: "Professional Python testing and automation.",
    duration: "5 weeks",
    level: "Intermediate",
    rating: 4.8,
    students: 430,
    price: "₹9,999",
    icon: "FaVial",
    color: "#0A9EDC",
    modules: defaultModules([
      "PyTest Fundamentals",
      "Assertions",
      "Fixtures",
      "Parameterization",
      "API Testing",
      "Test Reports",
      "Mocking",
      "Automation Project",
    ]),
    projects: [
      "API Automation",
      "Web Application Tests",
      "Python Test Framework",
    ],
    tools: ["Python", "PyTest", "VS Code", "Postman"],
    career: ["Automation Test Engineer", "Python QA Engineer", "SDET"],
    requirements: ["Python Programming", "Basic Testing Knowledge"],
    faqs: defaultFaqs("PyTest"),
  },
  {
    id: "ui-ux",
    title: "UI/UX Design",
    slug: "/courses/ui-ux",
    category: "Design",
    description:
      "Master UI/UX Design from beginner to advanced. Learn user research, wireframing, prototyping, design systems, typography, color theory, usability testing, and create modern user experiences using Figma and Adobe XD.",
    shortDescription: "Design beautiful and user-friendly digital experiences.",
    duration: "8 weeks",
    level: "Beginner",
    rating: 4.9,
    students: 760,
    price: "₹14,999",
    icon: "FaPalette",
    color: "#8B5CF6",
    modules: defaultModules([
      "UI/UX Fundamentals",
      "Design Principles",
      "Wireframing",
      "Prototyping",
      "Figma",
      "Design Systems",
      "Usability Testing",
      "Portfolio Project",
    ]),
    projects: ["Mobile App UI", "Website Redesign", "Dashboard Design"],
    tools: ["Figma", "Adobe XD", "Canva"],
    career: ["UI Designer", "UX Designer", "Product Designer"],
    requirements: ["Basic computer knowledge"],
    faqs: defaultFaqs("UI/UX Design"),
  },
];

export const getCourseById = (id: string) => COURSES.find((c) => c.id === id);
export const getPopularCourses = () =>
  COURSES.filter(
    (c) =>
      !["resume", "interview", "mock-interview", "soft-skills"].includes(c.id),
  ).slice(0, 6);
