import type { Course } from '../types';

const defaultModules = (topics: string[]) => [
  { title: 'Fundamentals', topics: topics.slice(0, 3), duration: '2 weeks' },
  { title: 'Core Concepts', topics: topics.slice(3, 6), duration: '3 weeks' },
  { title: 'Advanced Topics', topics: topics.slice(6), duration: '2 weeks' },
  { title: 'Projects & Assessment', topics: ['Capstone Project', 'Code Review', 'Final Assessment'], duration: '1 week' },
];

const defaultFaqs = (courseName: string) => [
  { question: `Do I need prior experience for ${courseName}?`, answer: 'No prior experience is required for our beginner courses. We start from the fundamentals and gradually progress to advanced topics.' },
  { question: 'Will I get a certificate?', answer: 'Yes, upon successful completion of the course and final project, you will receive an industry-recognized certificate from YahTecInfo.' },
  { question: 'Is placement assistance provided?', answer: 'Absolutely! We provide resume building, mock interviews, and direct referrals to our 50+ hiring partners.' },
  { question: 'Can I access recordings?', answer: 'Yes, all live sessions are recorded and available for lifetime access through our learning portal.' },
];

export const COURSES: Course[] = [
  {
    id: 'html-css', title: 'HTML & CSS', slug: '/courses/html-css', category: 'Frontend',
    description: 'Master the building blocks of the web. Learn semantic HTML5, modern CSS3, Flexbox, Grid, animations, and responsive design principles to create stunning websites.',
    shortDescription: 'Build beautiful, responsive websites from scratch.',
    duration: '6 weeks', level: 'Beginner', rating: 4.9, students: 1200, price: '₹9,999',
    icon: 'FaHtml5', color: '#E44D26',
    modules: defaultModules(['HTML5 Structure', 'Semantic Elements', 'Forms & Inputs', 'CSS Selectors', 'Flexbox Layout', 'CSS Grid', 'Animations', 'Responsive Design']),
    projects: ['Personal Portfolio', 'Landing Page', 'Dashboard UI'], tools: ['VS Code', 'Chrome DevTools', 'Figma'],
    career: ['Frontend Developer', 'UI Developer', 'Web Designer'], requirements: ['Basic computer knowledge', 'No coding experience needed'],
    faqs: defaultFaqs('HTML & CSS'),
  },
  {
    id: 'javascript', title: 'JavaScript', slug: '/courses/javascript', category: 'Frontend',
    description: 'Deep dive into JavaScript ES6+, DOM manipulation, async programming, APIs, and modern JavaScript patterns used in production applications.',
    shortDescription: 'Master the language of the web with modern JS.',
    duration: '8 weeks', level: 'Beginner', rating: 4.8, students: 980, price: '₹14,999',
    icon: 'FaJs', color: '#F7DF1E',
    modules: defaultModules(['Variables & Data Types', 'Functions & Scope', 'DOM Manipulation', 'ES6+ Features', 'Async/Await', 'Fetch API', 'Error Handling', 'Design Patterns']),
    projects: ['Todo App', 'Weather App', 'E-commerce Cart'], tools: ['VS Code', 'Node.js', 'Chrome DevTools'],
    career: ['JavaScript Developer', 'Frontend Developer', 'Full Stack Developer'], requirements: ['HTML & CSS basics'],
    faqs: defaultFaqs('JavaScript'),
  },
  {
    id: 'reactjs', title: 'React JS', slug: '/courses/reactjs', category: 'Frontend',
    description: 'Build modern, scalable web applications with React 19. Learn hooks, state management, routing, and best practices for enterprise applications.',
    shortDescription: 'Build dynamic UIs with the most popular framework.',
    duration: '10 weeks', level: 'Intermediate', rating: 4.9, students: 850, price: '₹19,999',
    icon: 'FaReact', color: '#61DAFB',
    modules: defaultModules(['JSX & Components', 'Props & State', 'Hooks Deep Dive', 'Context API', 'React Router', 'Performance', 'Testing', 'Deployment']),
    projects: ['Social Media App', 'Admin Dashboard', 'Real-time Chat App'], tools: ['VS Code', 'Vite', 'React DevTools'],
    career: ['React Developer', 'Frontend Engineer', 'Full Stack Developer'], requirements: ['JavaScript proficiency', 'HTML & CSS'],
    faqs: defaultFaqs('React JS'),
  },
  {
    id: 'java', title: 'Java Programming', slug: '/courses/java', category: 'Backend',
    description: 'Learn Java from fundamentals to advanced OOP, collections, multithreading, and design patterns used in enterprise software development.',
    shortDescription: 'Enterprise-grade programming with Java.',
    duration: '10 weeks', level: 'Beginner', rating: 4.7, students: 720, price: '₹17,999',
    icon: 'FaJava', color: '#007396',
    modules: defaultModules(['Java Basics', 'OOP Concepts', 'Collections Framework', 'Exception Handling', 'Multithreading', 'JDBC', 'Design Patterns', 'Project']),
    projects: ['Banking System', 'Library Management', 'E-commerce Backend'], tools: ['IntelliJ IDEA', 'Maven', 'Git'],
    career: ['Java Developer', 'Backend Engineer', 'Software Engineer'], requirements: ['Basic programming logic'],
    faqs: defaultFaqs('Java'),
  },
  {
    id: 'springboot', title: 'Spring Boot', slug: '/courses/springboot', category: 'Backend',
    description: 'Build production-ready REST APIs and microservices with Spring Boot, Spring Security, JPA, and cloud deployment strategies.',
    shortDescription: 'Enterprise backend development with Spring.',
    duration: '8 weeks', level: 'Intermediate', rating: 4.8, students: 560, price: '₹21,999',
    icon: 'SiSpringboot', color: '#6DB33F',
    modules: defaultModules(['Spring Core', 'Spring Boot Setup', 'REST APIs', 'Spring Security', 'JPA/Hibernate', 'Microservices', 'Testing', 'Deployment']),
    projects: ['REST API Service', 'Microservice Architecture', 'Auth System'], tools: ['IntelliJ IDEA', 'Postman', 'Docker'],
    career: ['Spring Developer', 'Backend Engineer', 'Microservices Architect'], requirements: ['Java proficiency'],
    faqs: defaultFaqs('Spring Boot'),
  },
  {
    id: 'python', title: 'Python', slug: '/courses/python', category: 'Backend',
    description: 'Master Python for web development, data analysis, automation, and scripting. From basics to building real-world applications.',
    shortDescription: 'Versatile programming for web, data & automation.',
    duration: '8 weeks', level: 'Beginner', rating: 4.8, students: 890, price: '₹15,999',
    icon: 'FaPython', color: '#3776AB',
    modules: defaultModules(['Python Basics', 'Data Structures', 'OOP in Python', 'File Handling', 'Web Scraping', 'Django Basics', 'API Development', 'Project']),
    projects: ['Web Scraper', 'Django Blog', 'Data Analysis Tool'], tools: ['PyCharm', 'Jupyter', 'pip'],
    career: ['Python Developer', 'Data Analyst', 'Automation Engineer'], requirements: ['Basic computer knowledge'],
    faqs: defaultFaqs('Python'),
  },
  {
    id: 'aws', title: 'AWS Cloud', slug: '/courses/aws', category: 'Cloud',
    description: 'Learn Amazon Web Services from EC2 to Lambda. Deploy, scale, and manage cloud infrastructure with hands-on labs.',
    shortDescription: 'Cloud computing with Amazon Web Services.',
    duration: '6 weeks', level: 'Intermediate', rating: 4.7, students: 430, price: '₹22,999',
    icon: 'FaAws', color: '#FF9900',
    modules: defaultModules(['Cloud Fundamentals', 'EC2 & VPC', 'S3 & Storage', 'RDS & Databases', 'Lambda & Serverless', 'IAM & Security', 'DevOps on AWS', 'Certification Prep']),
    projects: ['Deploy Web App', 'Serverless API', 'Multi-tier Architecture'], tools: ['AWS Console', 'AWS CLI', 'CloudFormation'],
    career: ['Cloud Engineer', 'DevOps Engineer', 'Solutions Architect'], requirements: ['Basic networking knowledge'],
    faqs: defaultFaqs('AWS'),
  },
  {
    id: 'testing', title: 'Software Testing', slug: '/courses/testing', category: 'QA',
    description: 'Comprehensive software testing course covering manual testing, test case design, bug reporting, and QA best practices.',
    shortDescription: 'Ensure quality with professional testing skills.',
    duration: '6 weeks', level: 'Beginner', rating: 4.6, students: 650, price: '₹12,999',
    icon: 'FaBug', color: '#FF6B6B',
    modules: defaultModules(['Testing Fundamentals', 'Test Case Design', 'Bug Life Cycle', 'Agile Testing', 'API Testing', 'Performance Basics', 'Test Management', 'Project']),
    projects: ['Test Plan Document', 'Bug Report Portfolio', 'API Test Suite'], tools: ['JIRA', 'Postman', 'TestRail'],
    career: ['QA Engineer', 'Test Analyst', 'QA Lead'], requirements: ['Basic software knowledge'],
    faqs: defaultFaqs('Software Testing'),
  },
  {
    id: 'automation', title: 'Test Automation', slug: '/courses/automation', category: 'QA',
    description: 'Automate testing with Selenium, Cypress, and JUnit. Build robust test frameworks for web and API automation.',
    shortDescription: 'Automate testing with industry tools.',
    duration: '8 weeks', level: 'Intermediate', rating: 4.8, students: 480, price: '₹18,999',
    icon: 'FaRobot', color: '#00FF99',
    modules: defaultModules(['Automation Basics', 'Selenium WebDriver', 'Page Object Model', 'Cypress', 'API Automation', 'Framework Design', 'CI/CD Integration', 'Project']),
    projects: ['Selenium Framework', 'Cypress E2E Suite', 'CI Pipeline'], tools: ['Selenium', 'Cypress', 'Jenkins'],
    career: ['Automation Engineer', 'SDET', 'QA Architect'], requirements: ['Java or JavaScript basics', 'Testing fundamentals'],
    faqs: defaultFaqs('Test Automation'),
  },
  {
    id: 'mysql', title: 'MySQL Database', slug: '/courses/mysql', category: 'Database',
    description: 'Master SQL queries, database design, normalization, stored procedures, and optimization for high-performance applications.',
    shortDescription: 'Database design and SQL mastery.',
    duration: '4 weeks', level: 'Beginner', rating: 4.7, students: 540, price: '₹9,999',
    icon: 'SiMysql', color: '#4479A1',
    modules: defaultModules(['SQL Basics', 'Joins & Subqueries', 'Database Design', 'Normalization', 'Stored Procedures', 'Indexing', 'Performance Tuning', 'Project']),
    projects: ['E-commerce DB Design', 'Reporting System', 'Data Migration'], tools: ['MySQL Workbench', 'phpMyAdmin', 'DBeaver'],
    career: ['Database Administrator', 'Backend Developer', 'Data Engineer'], requirements: ['Basic computer knowledge'],
    faqs: defaultFaqs('MySQL'),
  },
  {
    id: 'git', title: 'Git Version Control', slug: '/courses/git', category: 'DevOps',
    description: 'Learn Git workflows, branching strategies, merging, rebasing, and collaboration techniques used in professional development teams.',
    shortDescription: 'Professional version control with Git.',
    duration: '2 weeks', level: 'Beginner', rating: 4.9, students: 1100, price: '₹4,999',
    icon: 'FaGitAlt', color: '#F05032',
    modules: defaultModules(['Git Basics', 'Branching', 'Merging & Rebasing', 'Remote Repos', 'Git Flow', 'Conflict Resolution', 'Best Practices', 'Workshop']),
    projects: ['Team Collaboration Project', 'Open Source Contribution'], tools: ['Git', 'Git Bash', 'GitKraken'],
    career: ['Any Developer Role'], requirements: ['Basic computer knowledge'],
    faqs: defaultFaqs('Git'),
  },
  {
    id: 'github', title: 'GitHub', slug: '/courses/github', category: 'DevOps',
    description: 'Master GitHub for code hosting, pull requests, code reviews, GitHub Actions CI/CD, and open-source contribution.',
    shortDescription: 'Collaborate and deploy with GitHub.',
    duration: '2 weeks', level: 'Beginner', rating: 4.8, students: 950, price: '₹4,999',
    icon: 'FaGithub', color: '#FFFFFF',
    modules: defaultModules(['GitHub Setup', 'Repositories', 'Pull Requests', 'Code Reviews', 'GitHub Actions', 'Pages & Deployment', 'Open Source', 'Portfolio']),
    projects: ['Portfolio on GitHub Pages', 'CI/CD Pipeline'], tools: ['GitHub', 'GitHub Actions', 'GitHub Copilot'],
    career: ['Any Developer Role'], requirements: ['Git basics'],
    faqs: defaultFaqs('GitHub'),
  },
  {
    id: 'fullstack', title: 'Full Stack Development', slug: '/courses/fullstack', category: 'Full Stack',
    description: 'Complete full stack program covering React, Node.js, databases, and deployment. Build end-to-end applications from scratch.',
    shortDescription: 'End-to-end web development mastery.',
    duration: '16 weeks', level: 'Advanced', rating: 4.9, students: 620, price: '₹39,999',
    icon: 'FaLayerGroup', color: '#00E5FF',
    modules: defaultModules(['Frontend with React', 'Backend with Node.js', 'Database Design', 'Authentication', 'API Development', 'DevOps & Deployment', 'Capstone Project', 'Interview Prep']),
    projects: ['SaaS Application', 'Social Platform', 'E-commerce Platform'], tools: ['React', 'Node.js', 'MongoDB', 'AWS'],
    career: ['Full Stack Developer', 'Software Engineer', 'Tech Lead'], requirements: ['HTML, CSS, JavaScript basics'],
    faqs: defaultFaqs('Full Stack Development'),
  },
  {
    id: 'resume', title: 'Resume Building', slug: '/study', category: 'Career',
    description: 'Craft a professional tech resume that gets past ATS systems and impresses hiring managers.',
    shortDescription: 'Build a resume that gets you hired.',
    duration: '1 week', level: 'Beginner', rating: 4.8, students: 2000, price: 'Free',
    icon: 'FaFileAlt', color: '#FFD700',
    modules: [{ title: 'Resume Workshop', topics: ['ATS Optimization', 'Format & Structure', 'Skills Section', 'Project Showcase'], duration: '1 week' }],
    projects: ['Professional Resume'], tools: ['Canva', 'LinkedIn'], career: ['All Tech Roles'], requirements: ['None'],
    faqs: defaultFaqs('Resume Building'),
  },
  {
    id: 'interview', title: 'Interview Preparation', slug: '/study', category: 'Career',
    description: 'Comprehensive interview prep covering technical questions, coding challenges, and behavioral interviews.',
    shortDescription: 'Ace your tech interviews with confidence.',
    duration: '2 weeks', level: 'Intermediate', rating: 4.9, students: 1500, price: '₹7,999',
    icon: 'FaUserTie', color: '#8B5CF6',
    modules: [{ title: 'Interview Mastery', topics: ['Technical Questions', 'Coding Challenges', 'System Design', 'Behavioral Rounds'], duration: '2 weeks' }],
    projects: ['Interview Question Bank'], tools: ['LeetCode', 'HackerRank'], career: ['All Tech Roles'], requirements: ['Course completion in any tech stack'],
    faqs: defaultFaqs('Interview Preparation'),
  },
  {
    id: 'mock-interview', title: 'Mock Interview', slug: '/study', category: 'Career',
    description: 'Practice with industry experts in simulated interview environments with detailed feedback.',
    shortDescription: 'Real interview simulation with expert feedback.',
    duration: '1 week', level: 'Advanced', rating: 4.9, students: 800, price: '₹5,999',
    icon: 'FaComments', color: '#3B82F6',
    modules: [{ title: 'Mock Sessions', topics: ['HR Round', 'Technical Round', 'Coding Round', 'Feedback Session'], duration: '1 week' }],
    projects: ['Performance Report'], tools: ['Zoom', 'CoderPad'], career: ['All Tech Roles'], requirements: ['Interview prep completion'],
    faqs: defaultFaqs('Mock Interview'),
  },
  {
    id: 'soft-skills', title: 'Soft Skills', slug: '/study', category: 'Career',
    description: 'Develop communication, teamwork, leadership, and presentation skills essential for tech professionals.',
    shortDescription: 'Essential professional skills for tech careers.',
    duration: '2 weeks', level: 'Beginner', rating: 4.7, students: 1200, price: '₹6,999',
    icon: 'FaUsers', color: '#00FF99',
    modules: [{ title: 'Professional Development', topics: ['Communication', 'Teamwork', 'Leadership', 'Presentation Skills'], duration: '2 weeks' }],
    projects: ['Presentation Portfolio'], tools: ['PowerPoint', 'Zoom'], career: ['All Tech Roles'], requirements: ['None'],
    faqs: defaultFaqs('Soft Skills'),
  },
];

export const getCourseById = (id: string) => COURSES.find((c) => c.id === id);
export const getPopularCourses = () => COURSES.filter((c) => !['resume', 'interview', 'mock-interview', 'soft-skills'].includes(c.id)).slice(0, 6);
